---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQ/P7LA/WoTueEZf9Ts8UniqEvpBDlJpkFnK12DxIUSBSWjb6o6bFkOH9zYVYdv0wzWOn1tmwFhIsT03ODD/qrTtFw5PVM9RmwDNsXgAG+0znsqE9JJz/HZ/CBf/KEBBYDYXnEx3haUtM/gdAa1jF9OgKvIi3uoFOPX7avCLxqOMsbe1RrdzlBAoZTFDaLR49jWS01+lvB6utZ3HTJ78yJqFT6389u4RsUmqDucA1d8Jm4RBTB4c8gRTUklvYBE8TNVPsUILRN/7mKB+3SeIaMwzzOGUq/8+bXLom/84dJLZQiBBMnwenyGRZNX68GKK3v2RM2avsAoJPHlmScxUJPDasZEgt55pxvX1L6efIgCGVLRu6H4txy3QKqCqecu3pQuyMgn+7XGHRwh+6ihh1+h/seCAjvZLl/OiB8tkJYV6Ijs+cGqSAy1ZkMJZ3mVjbRkq2HQj4g71mkROW1mBpEG6B2FopfcMIuZxPjp+1oqU8WoeoKhdFbCzMChl6FYmvYqY/Xm4mXo5y2/s0blzeK06w52i123+woDBcGpDFCumGwFKvehMjqQmN3kbwaFwfkYOPNI7hWcNlp1/7pLxx48H01PLqkhI4tgKYpIE1ENZZfzK5o1BSSww2IXCnpXgg/QvlAVxsQ9g9L5qzV0UwK9HoZlBDPaiavkwbHqp/9VWcadilb6W5hgyJyN8CJ04zGz4A6JgzOHyyl2sINxYU=
    admin-user: AgC24I3QFZr1cl8lOijrdUcVfnW/2v1u3/l2zOc8QXSPOWw0YNIqZbSvTYusm+g+wHC6iCxtKI/Ev7GbfQzxlW7CumdbZlXuKLYyNfb8WkcoTOY01UlbU3QPd2W2rkCVGcU5VtNnAIiTombtNFnwygaqyYh4A2T4TxEnDHF2fWvtwK9ayV/AlaHSwIFFTIt2dC85KkrS1u96LRS5PVKE0jnIcd2M9LNtA1t0dIjEQT4eTgMkfWvDV8K8TVXFkOfkXxldqofRGp5fWZiARKOLYE3MGMIgGUZu1G+AYcbIT77wTlle+wqLtgmakborfJqddlo11w87yM08S0Uw08yTeq1ZXApNuGZryW3MJOBTYY1OIy3JQrvMT7P1v4wvYe1jnn6Gipi1/Ve/GzTkGjv4jMTzNX/Yn9QUewx+xjFMn0f5sMNDriPh4HKNlDfl7lLOzi5jEYPO6j+k/fZ5aU8Q34Ae3AjfDzMhuWYhPbb8bc5RG4ovQ2BJqpvTu8bkm/PGM4sdODBE9GJ6MTEdFbCPKTmua/mlmV6pOT3fD39lUuUbeDqdjIvXYeQxyuSfusvow6H02517b4vTDiVb4iHkazOlKfzlloOKqRxBUQJJFgDPObImHMFQp/iPrkw+PzCWaPeBDyDAs/AfmNReZICV65vuCVLqGMnMbEI2k6+RZeugdRODVmuhaiS3+hHe3DhhBTtFTg==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
