prometheus:
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  admin:
    existingSecret: grafana-admin-creds
    userKey: admin-user
    passwordKey: admin-password

alertmanager:
  enabled: false
  