apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd  
  annotations:
    argocd.argoproj.io/sync-wave: "-3" 
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.0.0
    helm:
      releaseName: argocd
      values: |
        server:
          insecure: true
        configs:
          params:
            server.insecure: true
          global:
            domain: argocd.local.elijahjohnson.dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false