apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: ollama  
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com
    targetRevision: 8.12.2
    helm:
      releaseName: open-webui
      values: |
        persistence:
          enabled: false
        tika:
          enabled: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true